### ISSUE TITLE
get() missing 1 required positional argument: 'user_id'

### ISSUE THREAD

**Issue by Tails** [bunq/tinker_python#17]
First, installed requirements using pip3. Then ran ```python3 ./tinker/create_production_configuration.py --api-key (API_KEY)``` to create a production context.

Then tried running ```python3 ./tinker/user_overview.py``` but it fails with following error. It seems the API now requires a user_id to be given up front in the constructor, instead of retrieving it from the created context.

```
Traceback (most recent call last):
  File "./tinker/user_overview.py", line 46, in <module>
    main()
  File "./tinker/user_overview.py", line 13, in main
    bunq = BunqLib(environment_type)
  File "/Users/l.dwaalmalefijt/Downloads/tinker_python-develop/tinker/libs/bunq_lib.py", line 54, in __init__
    self.setup_current_user()
  File "/Users/l.dwaalmalefijt/Downloads/tinker_python-develop/tinker/libs/bunq_lib.py", line 94, in setup_current_user
    user = endpoint.User.get().value.get_referenced_object()
TypeError: get() missing 1 required positional argument: 'user_id'
```

**Comment by OGKevin** [comment]
ah it seems that either 

1. tinker is using an outdated SDK version 
2. the SDK regeneration did not go as planned 😅 

Thanks for reporting.
