### ISSUE TITLE
Tinker scripts give ModuleNotFoundError: No module named 'bunq.sdk.client'

### ISSUE THREAD

**Issue by metawilm** [bunq/tinker_python#34]
Trying to get the tinker scripts to work in Python 3.8. In [setup.sh](https://github.com/bunq/tinker_python/blob/develop/setup.sh#L148) I changed it to include the interpreter: `PIPENV_VENV_IN_PROJECT=1 pipenv --python /usr/bin/python3 install`

The installation seems to succeed. However running the tinker scripts fail:
```
./tinker/update_account.py 
Traceback (most recent call last):
  File "./tinker/update_account.py", line 2, in <module>
    from libs.bunq_lib import BunqLib
  File "/home/dave2/b2/tinker/libs/bunq_lib.py", line 8, in <module>
    from bunq.sdk.client import Pagination
ModuleNotFoundError: No module named 'bunq.sdk.client'
```

**Comment by dev-goalz** [comment]
Having the same issue.

**Comment by leviouwendijk** [comment]
That's because Bunq's examples, so far as I can see, are still using outdated import statements. 

I did some pydoc digging, to see where the package contents *actually* are. I'll attach a .txt with the true bunq.sdk contents.

It implies that `Pagination` is actually in `bunq.sdk.http.pagination`. 

Thus: change the import statement from this:
`from bunq.sdk.client import Pagination` 
to this:
 `from bunq.sdk.http.pagination import Pagination`

Doing this has resolved the import error for me.

[bunq-sdk-corrected-import-package-listing.txt](https://github.com/bunq/tinker_python/files/14970775/bunq-sdk-corrected-import-package-listing.txt)
