### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by fira42073** [bunq/tinker_python#37]
I cannot run any of the code examples, seems like the sdk was updated, but tinker was not.

```~/.../bunq-tinker/tinker ( master U:2 ⊘ )
❯  python create_production_configuration.py
Traceback (most recent call last):
  File "/home/murr/Sandboxes/bunq-tinker/tinker/create_production_configuration.py", line 5, in <module>
    from bunq.sdk.context import ApiContext
ImportError: cannot import name 'ApiContext' from 'bunq.sdk.context' (/home/murr/.local/share/virtualenvs/bunq-tinker-B0ODIK44/lib64/python3.11/site-packages/bunq/sdk/context/__init__.py)

~/.../bunq-tinker/tinker ( master U:2 ⊘ )
❯  python user_overview.py
Traceback (most recent call last):
  File "/home/murr/Sandboxes/bunq-tinker/tinker/user_overview.py", line 2, in <module>
    from libs.bunq_lib import BunqLib
  File "/home/murr/Sandboxes/bunq-tinker/tinker/libs/bunq_lib.py", line 8, in <module>
    from bunq.sdk.client import Pagination
ModuleNotFoundError: No module named 'bunq.sdk.client'
```

**Comment by mjmare** [comment]
No, it uses python 3.6 and a old version of the Bunq API 1.13.1.
The whole Bunq SDK seems ancient.
